### ISSUE TITLE
Type '{ participants: true; }' is not assignable to type 'never'.ts(2322) (property) include: never

### ISSUE THREAD

**Issue by rodrigoricky** [JaleelB/callsquare#4]
Type '{ participants: true; }' is not assignable to type 'never'.ts(2322)
(property) include: never

![image](https://github.com/JaleelB/callsquare/assets/89636767/64934c25-95b6-4b8e-b3c4-5223f272af09)

**Comment by JaleelB** [comment]
Thank you for reporting this issue, and for providing the screenshot. To help me understand and resolve the problem, could you please provide more details?

- What were you doing when this issue occurred?
- Can you provide any error messages or logs?
- What browser and operating system are you using?
- Are there specific steps I can follow to reproduce the issue?

Any additional information you can provide will be very helpful.

**Comment by rodrigoricky** [comment]
This happened from a fresh installation, just after I setup the database then I tried to run it, it happened.

Commands I used on setting up prisma;

- yarn
- yarn prisma init
- yarn prisma migrate
- yarn prisma migrate dev
- yarn prisma db pull
- npm run build && npm start

**Comment by JaleelB** [comment]
> 

The error is likely happening because the Prisma Client that's being used to run the code doesn't match the Prisma schema. This can happen if the Prisma Client hasn't been regenerated after making changes to the schema.

Since you did a fresh clone and ran the Prisma setup commands, it's possible that the Prisma Client was not regenerated after running the migrations.

Here's what you can do to try and fix the issue:

1. You need to regenerate the Prisma Client to ensure that it matches the schema. You can do this by running the following command:
```
npx prisma generate
```
2. After regenerating the Prisma Client, you should rebuild the project to make sure that the newly generated client is being used. You can do this by running:
```
yarn build
```
3. Restart your development server to make sure that the changes are picked up.:
```
yarn dev
```

Also, based on the commands you listed, it seems you are using both npm and yarn at the same time, which I would recommend you not doing.
